version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankdemo
      MYSQL_USER: negasi
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"  # External MySQL port 3307, internal 3306
    networks:
      - my-network

  springboot-app:
    build: .
    container_name: my-spring-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankdemo
      SPRING_DATASOURCE_USERNAME: negasi
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9090:8080"  # External API port 9090, internal 8080
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
